service: helloworld

provider:
  name: aws
  runtime: go1.x
  memorySize: 128

package:
 exclude:
   - ./**
 include:
   - ./bin/**

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    certificateName: "*.danielspeixoto.com"
    domainName: helloworld.dev.danielspeixoto.com

functions:
  hello:
    handler: bin/hello
    events:
    - http: GET hello